version: '3.8'

services:
  api:
    build:
      target: base  # Use the base stage for development
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - DOTNET_USE_POLLING_FILE_WATCHER=true
      - ASPNETCORE_LOGGING__CONSOLE__DISABLECOLORS=false
    volumes:
      - ./StrengthPortal.Api:/app/source:cached
      - /app/source/bin
      - /app/source/obj
    ports:
      - "8080:8080"
      - "8081:8081"  # HTTPS port for development
    command: ["dotnet", "watch", "run", "--project", "/app/source", "--urls", "http://+:8080"]

  sqlserver:
    ports:
      - "1433:1433"  # Expose SQL Server port for local development tools
